// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: pdata.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pdata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Pdata   []byte `protobuf:"bytes,2,opt,name=pdata,proto3" json:"pdata,omitempty"`
	Ptype   string `protobuf:"bytes,3,opt,name=ptype,proto3" json:"ptype,omitempty"`
	KeyHash []byte `protobuf:"bytes,4,opt,name=keyHash,proto3" json:"keyHash,omitempty"`
}

func (x *Pdata) Reset() {
	*x = Pdata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pdata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pdata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pdata) ProtoMessage() {}

func (x *Pdata) ProtoReflect() protoreflect.Message {
	mi := &file_pdata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pdata.ProtoReflect.Descriptor instead.
func (*Pdata) Descriptor() ([]byte, []int) {
	return file_pdata_proto_rawDescGZIP(), []int{0}
}

func (x *Pdata) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Pdata) GetPdata() []byte {
	if x != nil {
		return x.Pdata
	}
	return nil
}

func (x *Pdata) GetPtype() string {
	if x != nil {
		return x.Ptype
	}
	return ""
}

func (x *Pdata) GetKeyHash() []byte {
	if x != nil {
		return x.KeyHash
	}
	return nil
}

type AddPdataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pdata *Pdata `protobuf:"bytes,1,opt,name=pdata,proto3" json:"pdata,omitempty"`
}

func (x *AddPdataRequest) Reset() {
	*x = AddPdataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pdata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPdataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPdataRequest) ProtoMessage() {}

func (x *AddPdataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPdataRequest.ProtoReflect.Descriptor instead.
func (*AddPdataRequest) Descriptor() ([]byte, []int) {
	return file_pdata_proto_rawDescGZIP(), []int{1}
}

func (x *AddPdataRequest) GetPdata() *Pdata {
	if x != nil {
		return x.Pdata
	}
	return nil
}

type AddPdataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *AddPdataResponse) Reset() {
	*x = AddPdataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pdata_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPdataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPdataResponse) ProtoMessage() {}

func (x *AddPdataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pdata_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPdataResponse.ProtoReflect.Descriptor instead.
func (*AddPdataResponse) Descriptor() ([]byte, []int) {
	return file_pdata_proto_rawDescGZIP(), []int{2}
}

func (x *AddPdataResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_pdata_proto protoreflect.FileDescriptor

var file_pdata_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a, 0x05, 0x50,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x48, 0x61, 0x73, 0x68,
	0x22, 0x2f, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x50, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x05, 0x70, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x06, 0x2e, 0x50, 0x64, 0x61, 0x74, 0x61, 0x52, 0x05, 0x70, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x39, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x50, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x40, 0x0a, 0x0b,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x31, 0x0a, 0x08, 0x41,
	0x64, 0x64, 0x50, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x41, 0x64, 0x64, 0x50,
	0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pdata_proto_rawDescOnce sync.Once
	file_pdata_proto_rawDescData = file_pdata_proto_rawDesc
)

func file_pdata_proto_rawDescGZIP() []byte {
	file_pdata_proto_rawDescOnce.Do(func() {
		file_pdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_pdata_proto_rawDescData)
	})
	return file_pdata_proto_rawDescData
}

var file_pdata_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pdata_proto_goTypes = []interface{}{
	(*Pdata)(nil),            // 0: Pdata
	(*AddPdataRequest)(nil),  // 1: AddPdataRequest
	(*AddPdataResponse)(nil), // 2: AddPdataResponse
	(*Response)(nil),         // 3: Response
}
var file_pdata_proto_depIdxs = []int32{
	0, // 0: AddPdataRequest.pdata:type_name -> Pdata
	3, // 1: AddPdataResponse.response:type_name -> Response
	1, // 2: PrivateData.AddPdata:input_type -> AddPdataRequest
	2, // 3: PrivateData.AddPdata:output_type -> AddPdataResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pdata_proto_init() }
func file_pdata_proto_init() {
	if File_pdata_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pdata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pdata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pdata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPdataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pdata_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPdataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pdata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pdata_proto_goTypes,
		DependencyIndexes: file_pdata_proto_depIdxs,
		MessageInfos:      file_pdata_proto_msgTypes,
	}.Build()
	File_pdata_proto = out.File
	file_pdata_proto_rawDesc = nil
	file_pdata_proto_goTypes = nil
	file_pdata_proto_depIdxs = nil
}
