name: autotests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  autotests:
    runs-on: ubuntu-latest
    container: golang:1.19

    services:
      postgres:
        image: postgres:15.1
        env:
          POSTGRES_USER: gophkeeper
          POSTGRES_PASSWORD: gophkeeper
          POSTGRES_DB: gophkeeper_test
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: make test
        env:
          GK_DB_TEST_DSN: 'postgres://gophkeeper:gophkeeper@postgres:5432/gophkeeper_test?sslmode=disable'
